services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brewery_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - app_var:/var/www/html/var
    networks:
      - test_demo_network
    depends_on:
      - mysql
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}?serverVersion=8.0&charset=utf8mb4"
    ports:
      - "8000:8080"



  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - test_demo_network
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment: 
      PMA_HOST: mysql
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - test_demo_network

volumes:
  mysql_data:

networks:
  test_demo_network: